controller_manager:
  ros__parameters:
    update_rate: 50
    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster
    joint1_position_controller:
      type: position_controllers/JointPositionController
      joint: joint1

joint1_position_controller:
  ros__parameters:
    use_sim_time: true
    position: 0.0